'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';

import { useT } from '../../i18n/provider';
import { api, ApiError } from '../../lib/api';

/**
 * Setting a password of your own.
 *
 * Reached automatically after the first sign-in, because the password that got
 * you here was generated by a script and printed to a terminal. Until it is
 * replaced the API refuses every other route, so this is not a suggestion the
 * panel makes — it is the only door out of it.
 *
 * It is also reachable on purpose from the products list, since the same screen
 * serves a routine change.
 */
export default function PasswordPage() {
  const router = useRouter();
  const t = useT('password');
  const c = useT('common');
  const [forced, setForced] = useState<boolean | null>(null);
  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    void (async () => {
      try {
        const me = await api.me();
        setForced(me.mustChangePassword);
      } catch {
        router.push('/login');
      }
    })();
  }, [router]);

  // Checked here as well as on the server so the mismatch is caught before a
  // password is sent anywhere.
  const tooShort = next.length > 0 && next.length < 12;
  const mismatch = confirm.length > 0 && confirm !== next;
  const ready = next.length >= 12 && confirm === next && current.length > 0;

  async function submit(event: React.FormEvent): Promise<void> {
    event.preventDefault();
    setError(null);
    setBusy(true);
    try {
      await api.changePassword(current, next);
      router.push('/products');
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : c('serviceUnreachable'));
      setCurrent('');
    } finally {
      setBusy(false);
    }
  }

  if (forced === null) return <main className="auth">{c('loading')}</main>;

  return (
    <main className="auth">
      <form
        onSubmit={(event) => {
          void submit(event);
        }}
        className="auth-card"
      >
        <h1>{forced ? t('titleForced') : t('titleRoutine')}</h1>

        {forced ? <p className="enroll-lede">{t('forcedLede')}</p> : null}

        <label>
          {t('current')}
          <input
            type="password"
            value={current}
            onChange={(event) => setCurrent(event.target.value)}
            autoComplete="current-password"
            required
            dir="ltr"
          />
        </label>

        <label>
          {t('next')}
          <input
            type="password"
            value={next}
            onChange={(event) => setNext(event.target.value)}
            autoComplete="new-password"
            minLength={12}
            required
            dir="ltr"
          />
        </label>
        {/* Length, not composition. A twelve-character passphrase beats eight
            characters with a digit and a symbol bolted on, and composition
            rules only ever teach people to write Password1!. */}
        <p className="enroll-hint">
          {tooShort ? t('tooShort', { length: next.length }) : t('lengthHint')}
        </p>

        <label>
          {t('confirm')}
          <input
            type="password"
            value={confirm}
            onChange={(event) => setConfirm(event.target.value)}
            autoComplete="new-password"
            required
            dir="ltr"
          />
        </label>
        {mismatch ? <p className="error">{t('mismatch')}</p> : null}

        {error ? <p className="error">{error}</p> : null}

        <p className="enroll-hint">{t('sessionsNotice')}</p>

        <button type="submit" disabled={busy || !ready}>
          {busy ? c('busy') : t('submit')}
        </button>
      </form>
    </main>
  );
}
