-- A staff password is generated by pnpm db:staff and printed once to a
-- terminal, which means it has been on a screen and in a scrollback before its
-- owner ever typed it. Treat it as an enrolment token rather than a password:
-- the session is issued, and every route except "change my password" refuses
-- until the owner has set one of their own.
ALTER TABLE "public"."StaffUser"
  ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "passwordChangedAt" TIMESTAMP(3);
