import { z } from 'zod';

import { localeSchema } from './primitives.js';

/**
 * The article studio (CR-0006): ideas for new articles drawn from what the
 * site already has, refined in a conversation with the model, and turned into
 * full draft articles — 1,500–2,000 words, a ~50-word summary first, headings,
 * an FAQ, SEO fields, and internal links that point only at products and
 * articles that exist. The article image is generated by the owner from a
 * prompt the studio writes, then uploaded in the article editor.
 *
 * There is no search-volume source connected (no Search Console, no keyword
 * tool), so ideas come from the site's own gaps and the model's knowledge of
 * how buyers search — the studio says so where it shows them.
 */

export const ARTICLE_LENGTH = { min: 1500, max: 2000 } as const;
/** Words in the opening summary the page shows as its lede. */
export const ARTICLE_SUMMARY_WORDS = 50;

export const ARTICLE_INTENTS = ['informational', 'how-to', 'comparison', 'commercial'] as const;
export const articleIntentSchema = z.enum(ARTICLE_INTENTS);

export const IDEA_STATUSES = ['NEW', 'DRAFTED', 'DISMISSED'] as const;

export const articleIdeaSchema = z.object({
  id: z.string(),
  title: z.string().trim().min(5).max(200),
  primaryKeyword: z.string().trim().min(2).max(120),
  secondaryKeywords: z.array(z.string().trim().min(2).max(120)).max(10),
  intent: articleIntentSchema,
  /** Why this article, against what the site already covers. */
  rationale: z.string().trim().max(600),
  outline: z.array(z.string().trim().min(2).max(200)).max(14),
  /** Only slugs that exist; anything else is dropped on the way in. */
  relatedProductSlugs: z.array(z.string()).max(8),
  relatedArticleSlugs: z.array(z.string()).max(8),
  locale: localeSchema,
  status: z.enum(IDEA_STATUSES),
  /** The draft written from it, once there is one. */
  articleSlug: z.string().nullable(),
  /** The image prompt written with the draft, kept for the owner. */
  imagePrompt: z.string().nullable(),
  createdAt: z.string(),
});
export type ArticleIdea = z.infer<typeof articleIdeaSchema>;

export const studioMessageSchema = z.object({
  role: z.enum(['user', 'assistant']),
  text: z.string().max(8000),
  at: z.string(),
});
export type StudioMessage = z.infer<typeof studioMessageSchema>;

export const studioStateSchema = z.object({
  ideas: z.array(articleIdeaSchema),
  thread: z.array(studioMessageSchema),
});
export type StudioState = z.infer<typeof studioStateSchema>;

export const STUDIO_STATE_KEY = 'studio.state';

export const studioViewSchema = studioStateSchema.extend({
  inventory: z.object({
    products: z.number().int(),
    articles: z.number().int(),
    publishedArticles: z.number().int(),
  }),
  aiReady: z.boolean(),
});
export type StudioView = z.infer<typeof studioViewSchema>;

export const studioChatSchema = z.object({
  /** Empty asks for a fresh set of ideas from the inventory alone. */
  message: z.string().trim().max(2000).default(''),
  locale: localeSchema.default('ar'),
});
export type StudioChat = z.infer<typeof studioChatSchema>;

export const setIdeaStatusSchema = z.object({ status: z.enum(['NEW', 'DISMISSED']) });

export const writeArticleSchema = z
  .object({
    ideaId: z.string().optional(),
    /** For an article that did not come from an idea. */
    title: z.string().trim().min(5).max(200).optional(),
    primaryKeyword: z.string().trim().max(120).optional(),
    locale: localeSchema.default('ar'),
    instructions: z.string().trim().max(1500).default(''),
  })
  .refine((value) => Boolean(value.ideaId ?? value.title), {
    message: 'اختر فكرة أو اكتب عنواناً.',
  });
export type WriteArticle = z.infer<typeof writeArticleSchema>;

export const studioArticleResultSchema = z.object({
  slug: z.string(),
  title: z.string(),
  locale: localeSchema,
  wordCount: z.number().int(),
  summaryWords: z.number().int(),
  internalLinks: z.array(z.string()),
  relatedProducts: z.array(z.string()),
  imagePrompt: z.string(),
  imageAlt: z.string(),
  notes: z.array(z.string()),
});
export type StudioArticleResult = z.infer<typeof studioArticleResultSchema>;

export const studioChatResultSchema = z.object({
  reply: z.string(),
  ideas: z.number().int(),
});

export const studioJobSchema = z.object({
  id: z.string(),
  kind: z.enum(['chat', 'article']),
  status: z.enum(['RUNNING', 'DONE', 'FAILED']),
  startedAt: z.string(),
  finishedAt: z.string().nullable(),
  result: z.union([studioArticleResultSchema, studioChatResultSchema]).nullable(),
  error: z.string().nullable(),
});
export type StudioJob = z.infer<typeof studioJobSchema>;

export const studioJobKey = (id: string): string => `studio.job.${id}`;

// --- the article image --------------------------------------------------------

export const articleHeroUploadSchema = z.object({
  dataUrl: z.string().min(32).max(1_950_000),
  alt: z.object({ ar: z.string().trim().max(300), en: z.string().trim().max(300) }),
});
export type ArticleHeroUpload = z.infer<typeof articleHeroUploadSchema>;

export const articleHeroSchema = z.object({
  url: z.string(),
  width: z.number().int(),
  height: z.number().int(),
  alt: z.string(),
});
export type ArticleHero = z.infer<typeof articleHeroSchema>;
