import type { ProductReviews, PublicReview } from '@da/contracts';

/**
 * What buyers said, on the product page.
 *
 * Every row here came from a delivered order line, and the section says so in
 * words rather than with a badge nobody reads. That sentence is the product
 * being sold as much as the licence is: the store this replaces carried 565
 * reviews generated by a plugin, and the only way a visitor can tell the
 * difference is if the page states the rule it follows.
 *
 * When there are no reviews the section still renders, and still says nothing
 * false. "No reviews yet — we only publish reviews from real purchases" is a
 * better answer than five hollow stars, and it is the honest explanation of
 * why a store that has been trading for years shows none.
 */
export function Reviews({ reviews, locale }: { reviews: ProductReviews; locale: string }) {
  const ar = locale === 'ar';
  const { aggregate, rows } = reviews;

  return (
    <section className="prose reviews" id="reviews">
      <h2>{ar ? 'آراء المشترين' : 'What buyers say'}</h2>

      {aggregate.count > 0 ? (
        <div className="review-summary">
          <p className="review-average">
            <strong>{aggregate.average}</strong>
            <Stars rating={Math.round(Number(aggregate.average))} locale={locale} />
          </p>
          <p className="review-count">
            {ar
              ? `${String(aggregate.count)} تقييماً من مشترين فعليين`
              : `${String(aggregate.count)} ${aggregate.count === 1 ? 'review' : 'reviews'} from verified purchases`}
          </p>
        </div>
      ) : (
        <p className="review-empty">
          {ar
            ? 'لا تقييمات بعد. لا ننشر إلا تقييمات من اشتروا المنتج فعلاً، ولا نشتري تقييماً بخصم.'
            : 'No reviews yet. We publish reviews only from people who actually bought the product, and we never trade a discount for one.'}
        </p>
      )}

      {rows.length > 0 ? (
        <ul className="review-list">
          {rows.map((review) => (
            <ReviewItem key={review.id} review={review} locale={locale} />
          ))}
        </ul>
      ) : null}

      {reviews.total > rows.length ? (
        <p className="review-more">
          {ar
            ? `تُعرض ${String(rows.length)} من ${String(reviews.total)} تقييماً.`
            : `Showing ${String(rows.length)} of ${String(reviews.total)} reviews.`}
        </p>
      ) : null}
    </section>
  );
}

function ReviewItem({ review, locale }: { review: PublicReview; locale: string }) {
  const ar = locale === 'ar';

  return (
    <li className="review">
      <Stars rating={review.rating} locale={locale} />
      {review.title ? (
        <p className="review-title" dir="auto">
          {review.title}
        </p>
      ) : null}

      {/* `dir` from the review's own locale, not the page's: an English review
          on the Arabic page is still an English paragraph, and inheriting rtl
          puts its full stop on the wrong side. */}
      <p className="review-body" dir={review.locale === 'en' ? 'ltr' : 'rtl'}>
        {review.body}
      </p>

      <p className="review-meta">
        <span>{review.authorName ?? (ar ? 'مشترٍ مُوثَّق' : 'Verified buyer')}</span>
        <span className="review-verified">{ar ? 'شراء موثّق' : 'Verified purchase'}</span>
        <time dateTime={review.createdAt}>{review.createdAt.slice(0, 10)}</time>
      </p>

      {review.storeReply ? (
        <div className="review-reply">
          <p className="review-reply-who">{ar ? 'ردّ المتجر' : 'Reply from the store'}</p>
          <p dir="auto">{review.storeReply}</p>
        </div>
      ) : null}
    </li>
  );
}

/**
 * The rating, drawn once and labelled for anything that is not looking at it.
 *
 * The stars are `aria-hidden` and the number beside them is the accessible
 * name, because "★★★★☆" read aloud is five identical symbols.
 */
function Stars({ rating, locale }: { rating: number; locale: string }) {
  const full = Math.max(1, Math.min(5, rating));
  const label = locale === 'ar' ? `${String(full)} من 5` : `${String(full)} out of 5`;

  return (
    <span className="stars" role="img" aria-label={label}>
      <span aria-hidden="true">{'★'.repeat(full).padEnd(5, '☆')}</span>
    </span>
  );
}
