import type { ProductReviews, PublicReview } from '@da/contracts';
import { useTranslations } from 'next-intl';

import { isArabic } from '../i18n/locale';

/**
 * What buyers said, on the product page.
 *
 * Every row here came from a delivered order line, and the section says so in
 * words rather than with a badge nobody reads. That sentence is the product
 * being sold as much as the licence is: the store this replaces carried 565
 * reviews generated by a plugin, and the only way a visitor can tell the
 * difference is if the page states the rule it follows.
 *
 * When there are no reviews the section still renders, and still says nothing
 * false. "No reviews yet — we only publish reviews from real purchases" is a
 * better answer than five hollow stars, and it is the honest explanation of
 * why a store that has been trading for years shows none.
 */
export function Reviews({ reviews }: { reviews: ProductReviews }) {
  const t = useTranslations('reviews');
  const { aggregate, rows } = reviews;

  return (
    <section className="prose reviews" id="reviews">
      <h2>{t('title')}</h2>

      {aggregate.count > 0 ? (
        <div className="review-summary">
          <p className="review-average">
            <strong>{aggregate.average}</strong>
            <Stars rating={Math.round(Number(aggregate.average))} />
          </p>
          <p className="review-count">{t('count', { count: aggregate.count })}</p>
        </div>
      ) : (
        <p className="review-empty">{t('empty')}</p>
      )}

      {rows.length > 0 ? (
        <ul className="review-list">
          {rows.map((review) => (
            <ReviewItem key={review.id} review={review} />
          ))}
        </ul>
      ) : null}

      {reviews.total > rows.length ? (
        <p className="review-more">
          {t('showing', { shown: String(rows.length), total: reviews.total })}
        </p>
      ) : null}
    </section>
  );
}

function ReviewItem({ review }: { review: PublicReview }) {
  const t = useTranslations('reviews');

  return (
    <li className="review">
      <Stars rating={review.rating} />
      {review.title ? (
        <p className="review-title" dir="auto">
          {review.title}
        </p>
      ) : null}

      {/* `dir` from the review's own locale, not the page's: an English review
          on the Arabic page is still an English paragraph, and inheriting rtl
          puts its full stop on the wrong side. */}
      <p className="review-body" dir={isArabic(review.locale) ? 'rtl' : 'ltr'}>
        {review.body}
      </p>

      <p className="review-meta">
        <span>{review.authorName ?? t('verifiedBuyer')}</span>
        <span className="review-verified">{t('verifiedPurchase')}</span>
        <time dateTime={review.createdAt}>{review.createdAt.slice(0, 10)}</time>
      </p>

      {review.storeReply ? (
        <div className="review-reply">
          <p className="review-reply-who">{t('storeReply')}</p>
          <p dir="auto">{review.storeReply}</p>
        </div>
      ) : null}
    </li>
  );
}

/**
 * The rating, drawn once and labelled for anything that is not looking at it.
 *
 * The stars are `aria-hidden` and the number beside them is the accessible
 * name, because "★★★★☆" read aloud is five identical symbols.
 */
function Stars({ rating }: { rating: number }) {
  const t = useTranslations('reviews');
  const full = Math.max(1, Math.min(5, rating));
  const label = t('stars', { rating: String(full) });

  return (
    <span className="stars" role="img" aria-label={label}>
      <span aria-hidden="true">{'★'.repeat(full).padEnd(5, '☆')}</span>
    </span>
  );
}
