import type { ProductReviews, PublicReview } from '@da/contracts';
import { useTranslations } from 'next-intl';

import { isArabic } from '../i18n/locale';

import { StarIcon } from './icons';

/**
 * What buyers said, on the product page — as the kit's `review` cards
 * (`02_Components/*\/review`): an avatar with the initial, the name, the
 * stars, the words; three to a row on a wide screen.
 *
 * Every row here came from a delivered order line, and the section says so in
 * words rather than with a badge nobody reads. That sentence is the product
 * being sold as much as the licence is: the store this replaces carried 565
 * reviews generated by a plugin, and the only way a visitor can tell the
 * difference is if the page states the rule it follows.
 *
 * When there are no reviews the section still renders, and still says nothing
 * false. "No reviews yet — we only publish reviews from real purchases" is a
 * better answer than five hollow stars.
 */
export function Reviews({ reviews }: { reviews: ProductReviews }) {
  const t = useTranslations('reviews');
  const { aggregate, rows } = reviews;

  return (
    <section className="reviews" id="reviews">
      <header className="section-head">
        <div className="section-head-text">
          <h2>{t('title')}</h2>
          {aggregate.count > 0 ? (
            <p className="review-summary">
              <Stars rating={Math.round(Number(aggregate.average))} />
              <strong className="review-average">{aggregate.average}</strong>
              <span>{t('count', { count: aggregate.count })}</span>
            </p>
          ) : null}
        </div>
      </header>

      {aggregate.count === 0 ? <p className="review-empty">{t('empty')}</p> : null}

      {rows.length > 0 ? (
        <ul className="review-list">
          {rows.map((review) => (
            <ReviewItem key={review.id} review={review} />
          ))}
        </ul>
      ) : null}

      {reviews.total > rows.length ? (
        <p className="review-more">
          {t('showing', { shown: String(rows.length), total: reviews.total })}
        </p>
      ) : null}
    </section>
  );
}

function ReviewItem({ review }: { review: PublicReview }) {
  const t = useTranslations('reviews');
  const name = review.authorName ?? t('verifiedBuyer');
  const initial = (review.authorName ?? t('anonymous')).trim().charAt(0);

  return (
    <li className="review">
      <div className="review-head">
        <span className="avatar" aria-hidden="true">
          {initial}
        </span>
        <div>
          <p className="review-name">{name}</p>
          <p className="review-meta">
            <span className="review-verified">{t('verifiedPurchase')}</span>
            <time dateTime={review.createdAt}>{review.createdAt.slice(0, 10)}</time>
          </p>
        </div>
      </div>

      <Stars rating={review.rating} />

      {review.title ? (
        <p className="review-title" dir="auto">
          {review.title}
        </p>
      ) : null}

      {/* `dir` from the review's own locale, not the page's: an English review
          on the Arabic page is still an English paragraph, and inheriting rtl
          puts its full stop on the wrong side. */}
      <p className="review-body" dir={isArabic(review.locale) ? 'rtl' : 'ltr'}>
        {review.body}
      </p>

      {review.storeReply ? (
        <div className="review-reply">
          <p className="review-reply-who">{t('storeReply')}</p>
          <p dir="auto">{review.storeReply}</p>
        </div>
      ) : null}
    </li>
  );
}

/**
 * The rating, drawn once and labelled for anything that is not looking at it.
 *
 * The stars are `aria-hidden` and the label is the accessible name, because
 * five identical symbols read aloud say nothing.
 */
function Stars({ rating }: { rating: number }) {
  const t = useTranslations('reviews');
  const full = Math.max(1, Math.min(5, rating));
  const label = t('stars', { rating: String(full) });

  return (
    <span className="stars" role="img" aria-label={label}>
      {[1, 2, 3, 4, 5].map((n) => (
        <span key={n} className={n <= full ? 'star is-on' : 'star'} aria-hidden="true">
          <StarIcon />
        </span>
      ))}
    </span>
  );
}
