import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';

import {
  ROUTES,
  type AdminReviewList,
  type AdminReviewQuery,
  type EditReview,
  type OwnReview,
  type ProductReviews,
  type PublicReview,
  type ReviewableList,
  type SubmitReview,
} from '@da/contracts';
import { FulfillmentState, Locale, Prisma, ReviewStatus } from '@da/db';

import { AuditService } from '../auth/audit.service.js';
import { MailService } from '../mail/mail.service.js';
import { reviewInvite } from '../mail/templates.js';
import { PrismaService } from '../prisma/prisma.service.js';

/**
 * Reviews, from the order line they belong to outwards.
 *
 * The legacy store shipped 565 rows generated by a plugin whose job is to
 * invent them. Nothing in this file can produce a review any other way than
 * from a `DELIVERED` order line owned by the session making the request:
 * `create` is called in exactly one place, it always reads the line first, and
 * the line always comes from a `where` clause that includes the customer id.
 * The database agrees — `Review.orderItemId` is required and unique, so a
 * second review on one line fails at the constraint rather than at a check
 * somebody can forget to write.
 *
 * Everything starts PENDING and nothing is published by the act of writing it.
 * That is not distrust of customers; it is that a store which sells licence
 * keys attracts review spam carrying links, and a queue somebody works is
 * cheaper than a published page somebody has to clean.
 *
 * `Product.ratingAvg` and `ratingCount` are recomputed from the approved rows
 * on every decision that changes which rows are approved. They are a cache of
 * this table and never a second opinion: a card showing 4.8 beside a list
 * averaging 4.2 is the same class of defect as the legacy product page whose
 * two JSON-LD blocks disagreed about the price.
 */

/** A moderated review cannot be edited; a PENDING one is still the author's. */
function editable(status: ReviewStatus): boolean {
  return status === ReviewStatus.PENDING;
}

function toLocale(locale: Locale): 'ar' | 'en' {
  return locale === Locale.EN ? 'en' : 'ar';
}

@Injectable()
export class ReviewsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly mail: MailService,
  ) {}

  // --- the customer's own ---------------------------------------------------

  /**
   * The lines this customer may review, and what they have already said.
   *
   * Delivered lines only, and every one of them is listed whether or not it
   * has a review — the list is also how somebody finds the review they wrote
   * last week to fix a typo in it.
   */
  async reviewable(customerId: string): Promise<ReviewableList> {
    const items = await this.prisma.client.orderItem.findMany({
      where: {
        fulfillmentState: FulfillmentState.DELIVERED,
        order: { customerId },
      },
      orderBy: { deliveredAt: 'desc' },
      select: {
        id: true,
        productNameSnapshot: true,
        deliveredAt: true,
        order: { select: { number: true } },
        variant: { select: { product: { select: { slug: true } } } },
        reviews: true,
      },
    });

    const rows = items.map((item) => {
      // One per line at the database level; the relation is a list because
      // that is how the generated client models it.
      const review = item.reviews[0];
      return {
        orderItemId: item.id,
        orderNumber: item.order.number,
        productSlug: item.variant.product.slug,
        productName: item.productNameSnapshot,
        // Non-null by the DELIVERED filter above, but the column is nullable.
        deliveredAt: (item.deliveredAt ?? new Date()).toISOString(),
        review: review ? this.toOwnReview(review) : null,
      };
    });

    return { rows, awaiting: rows.filter((row) => row.review === null).length };
  }

  /**
   * Writes one review for one delivered line.
   *
   * The line is looked up by id *and* customer id together. A two-step "find
   * the line, then check who owns it" is the same query with a gap in the
   * middle, and this one has no gap: a line belonging to somebody else gets
   * the same answer as a line that does not exist.
   */
  async submit(input: {
    customerId: string;
    orderItemId: string;
    review: SubmitReview;
  }): Promise<OwnReview> {
    const item = await this.prisma.client.orderItem.findFirst({
      where: { id: input.orderItemId, order: { customerId: input.customerId } },
      select: {
        id: true,
        orderId: true,
        fulfillmentState: true,
        variant: { select: { productId: true } },
        reviews: { select: { id: true } },
      },
    });
    if (!item) throw new NotFoundException('لا يوجد هذا البند في طلباتك.');

    if (item.fulfillmentState !== FulfillmentState.DELIVERED) {
      throw new BadRequestException('لم يُسلَّم هذا البند بعد، فلا شيء لتقييمه.');
    }
    if (item.reviews.length > 0) {
      throw new BadRequestException('لديك تقييم لهذا البند بالفعل. يمكنك تعديله بدل كتابة آخر.');
    }

    const created = await this.prisma.client.review.create({
      data: {
        productId: item.variant.productId,
        orderItemId: item.id,
        customerId: input.customerId,
        rating: input.review.rating,
        title: input.review.title ?? null,
        body: input.review.body,
        locale: input.review.locale === 'en' ? Locale.EN : Locale.AR,
        // Not a parameter. A submission that could choose its own status is a
        // submission that can publish itself.
        status: ReviewStatus.PENDING,
      },
    });

    // The invitation that produced this, if there was one, is answered. Marked
    // on the order rather than the line: the email asks about the order, and a
    // customer who answers it for one of two lines has still answered it.
    await this.prisma.client.reviewInvite.updateMany({
      where: { orderId: item.orderId, customerId: input.customerId, respondedAt: null },
      data: { respondedAt: new Date() },
    });

    return this.toOwnReview(created);
  }

  /**
   * Edits a review while it is still waiting to be read.
   *
   * Once moderated it is frozen. An approved review that its author can still
   * rewrite is a published page anybody who bought one licence can change at
   * will, and re-queueing it on every edit would mean a moderator reads the
   * same review until the author stops.
   */
  async edit(input: {
    customerId: string;
    orderItemId: string;
    patch: EditReview;
  }): Promise<OwnReview> {
    const existing = await this.prisma.client.review.findFirst({
      where: { orderItemId: input.orderItemId, customerId: input.customerId },
    });
    if (!existing) throw new NotFoundException('لا يوجد تقييم منك لهذا البند.');

    if (!editable(existing.status)) {
      throw new ForbiddenException(
        'تمّت مراجعة هذا التقييم، ولم يعد قابلاً للتعديل. راسِل الدعم إن أردت حذفه.',
      );
    }

    const updated = await this.prisma.client.review.update({
      where: { id: existing.id },
      data: {
        ...(input.patch.rating === undefined ? {} : { rating: input.patch.rating }),
        ...(input.patch.title === undefined ? {} : { title: input.patch.title }),
        ...(input.patch.body === undefined ? {} : { body: input.patch.body }),
      },
    });

    return this.toOwnReview(updated);
  }

  private toOwnReview(row: {
    id: string;
    rating: number;
    title: string | null;
    body: string;
    locale: Locale;
    status: ReviewStatus;
    storeReply: string | null;
    createdAt: Date;
  }): OwnReview {
    return {
      id: row.id,
      rating: row.rating,
      title: row.title,
      body: row.body,
      locale: toLocale(row.locale),
      status: row.status,
      storeReply: row.storeReply,
      createdAt: row.createdAt.toISOString(),
      editable: editable(row.status),
    };
  }

  // --- what the storefront shows -------------------------------------------

  /**
   * Published reviews for one product, with the aggregate over the same rows.
   *
   * The aggregate is computed here rather than read from `Product`, so the
   * number under the stars and the number in the structured data are the same
   * arithmetic over the same `status = APPROVED` filter. The denormalised
   * columns exist for product cards, which cannot afford a second query — and
   * they are written from this same filter whenever a decision changes it.
   */
  async forProduct(slug: string, page: number, perPage: number): Promise<ProductReviews> {
    const product = await this.prisma.client.product.findUnique({
      where: { slug },
      select: { id: true },
    });
    if (!product) throw new NotFoundException(`No product with slug "${slug}"`);

    const where = { productId: product.id, status: ReviewStatus.APPROVED };

    const [rows, total, aggregate] = await Promise.all([
      this.prisma.client.review.findMany({
        where,
        // Newest first: a store selling annual licences is judged on whether
        // last month's keys worked, not on a five-star review from 2023.
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * perPage,
        take: perPage,
        select: {
          id: true,
          rating: true,
          title: true,
          body: true,
          locale: true,
          createdAt: true,
          storeReply: true,
          repliedAt: true,
          customer: { select: { firstName: true } },
        },
      }),
      this.prisma.client.review.count({ where }),
      this.prisma.client.review.aggregate({ where, _avg: { rating: true } }),
    ]);

    return {
      slug,
      rows: rows.map((row): PublicReview => ({
        id: row.id,
        rating: row.rating,
        title: row.title,
        body: row.body,
        locale: toLocale(row.locale),
        // First name or nothing. The claim this list makes is "these people
        // bought it", and a full name next to it adds nothing to that while
        // publishing something the customer never agreed to publish.
        authorName: row.customer.firstName,
        createdAt: row.createdAt.toISOString(),
        storeReply: row.storeReply,
        repliedAt: row.repliedAt?.toISOString() ?? null,
      })),
      page,
      perPage,
      total,
      aggregate: { count: total, average: (aggregate._avg.rating ?? 0).toFixed(2) },
    };
  }

  // --- moderation -----------------------------------------------------------

  async list(query: AdminReviewQuery): Promise<AdminReviewList> {
    const status = ReviewStatus[query.status];

    const [rows, pending, approved, rejected] = await Promise.all([
      this.prisma.client.review.findMany({
        where: { status },
        // Oldest first while pending: a queue is worked by answering whoever
        // has waited longest, and a review nobody reads is a customer who
        // wrote one for nothing.
        orderBy: { createdAt: status === ReviewStatus.PENDING ? 'asc' : 'desc' },
        take: query.limit,
        select: {
          id: true,
          status: true,
          rating: true,
          title: true,
          body: true,
          locale: true,
          storeReply: true,
          repliedAt: true,
          createdAt: true,
          customer: { select: { firstName: true, email: true } },
          orderItem: {
            select: {
              productNameSnapshot: true,
              deliveredAt: true,
              order: { select: { number: true } },
            },
          },
          product: { select: { slug: true } },
        },
      }),
      this.prisma.client.review.count({ where: { status: ReviewStatus.PENDING } }),
      this.prisma.client.review.count({ where: { status: ReviewStatus.APPROVED } }),
      this.prisma.client.review.count({ where: { status: ReviewStatus.REJECTED } }),
    ]);

    return {
      rows: rows.map((row) => ({
        id: row.id,
        status: row.status,
        rating: row.rating,
        title: row.title,
        body: row.body,
        locale: toLocale(row.locale),
        productSlug: row.product.slug,
        productName: row.orderItem.productNameSnapshot,
        orderNumber: row.orderItem.order.number,
        deliveredAt: row.orderItem.deliveredAt?.toISOString() ?? null,
        customerName: row.customer.firstName,
        customerEmail: row.customer.email,
        storeReply: row.storeReply,
        repliedAt: row.repliedAt?.toISOString() ?? null,
        createdAt: row.createdAt.toISOString(),
      })),
      counts: { pending, approved, rejected },
    };
  }

  /**
   * Approves or rejects one review, and audits the decision.
   *
   * Both directions recompute the product's rating, including rejection: a
   * review taken down after publication has to take its star with it, and a
   * cached average that outlives the row it was computed from is how a page
   * ends up claiming a rating no visible review supports.
   */
  async moderate(input: {
    id: string;
    status: 'APPROVED' | 'REJECTED';
    staffId: string;
    ip?: string | undefined;
    userAgent?: string | undefined;
  }): Promise<{ id: string; status: ReviewStatus; ratingCount: number; ratingAvg: string }> {
    const existing = await this.prisma.client.review.findUnique({
      where: { id: input.id },
      select: { id: true, status: true, productId: true, rating: true },
    });
    if (!existing) throw new NotFoundException('لا يوجد تقييم بهذا المعرّف.');

    const next = ReviewStatus[input.status];

    const updated = await this.prisma.client.review.update({
      where: { id: existing.id },
      data: { status: next, moderatedById: input.staffId },
      select: { id: true, status: true, productId: true },
    });

    const rating = await this.recompute(updated.productId);

    await this.audit.record({
      actorId: input.staffId,
      entity: 'Review',
      entityId: updated.id,
      action: next === ReviewStatus.APPROVED ? 'review.approve' : 'review.reject',
      before: { status: existing.status, rating: existing.rating },
      after: { status: next, ratingCount: rating.count, ratingAvg: rating.average },
      ip: input.ip,
      userAgent: input.userAgent,
    });

    return {
      id: updated.id,
      status: updated.status,
      ratingCount: rating.count,
      ratingAvg: rating.average,
    };
  }

  /**
   * The store's answer, printed under the review.
   *
   * A reply never changes the review it answers. The only thing worth doing
   * with a bad review is replying to it in public, and a store that could edit
   * one instead is back where the legacy store was.
   */
  async reply(input: {
    id: string;
    body: string;
    staffId: string;
    ip?: string | undefined;
    userAgent?: string | undefined;
  }): Promise<{ id: string; storeReply: string; repliedAt: string }> {
    const existing = await this.prisma.client.review.findUnique({
      where: { id: input.id },
      select: { id: true, storeReply: true },
    });
    if (!existing) throw new NotFoundException('لا يوجد تقييم بهذا المعرّف.');

    const updated = await this.prisma.client.review.update({
      where: { id: existing.id },
      data: { storeReply: input.body, repliedAt: new Date() },
      select: { id: true, storeReply: true, repliedAt: true },
    });

    await this.audit.record({
      actorId: input.staffId,
      entity: 'Review',
      entityId: updated.id,
      action: 'review.reply',
      before: { storeReply: existing.storeReply },
      after: { storeReply: input.body },
      ip: input.ip,
      userAgent: input.userAgent,
    });

    return {
      id: updated.id,
      storeReply: updated.storeReply ?? input.body,
      repliedAt: (updated.repliedAt ?? new Date()).toISOString(),
    };
  }

  /**
   * Rewrites the two denormalised columns from the approved rows.
   *
   * Called after every decision rather than on a schedule. `ratingAvg` is
   * `Decimal(3,2)`, so the value is rounded here instead of leaving Postgres
   * to truncate a float nobody chose the precision of.
   */
  private async recompute(productId: string): Promise<{ count: number; average: string }> {
    const aggregate = await this.prisma.client.review.aggregate({
      where: { productId, status: ReviewStatus.APPROVED },
      _avg: { rating: true },
      _count: { _all: true },
    });

    const count = aggregate._count._all;
    const average = count > 0 ? (aggregate._avg.rating ?? 0).toFixed(2) : '0.00';

    await this.prisma.client.product.update({
      where: { id: productId },
      data: { ratingAvg: new Prisma.Decimal(average), ratingCount: count },
    });

    return { count, average };
  }

  // --- asking for one -------------------------------------------------------

  /**
   * Invites the buyer of a delivered order to review what they bought.
   *
   * This is the only mechanism by which the store accumulates ratings, which
   * is why it is worth building and the plugin was not: a review that exists
   * because somebody was asked is still a review somebody wrote.
   *
   * Nothing calls this yet — see the module comment. It is idempotent per
   * order and stage through `ReviewInvite`'s unique constraint, so a caller
   * that fires twice sends once.
   */
  async invite(input: { orderId: string; stage?: number }): Promise<{ sent: boolean }> {
    const stage = input.stage ?? 1;

    const order = await this.prisma.client.order.findUnique({
      where: { id: input.orderId },
      select: {
        id: true,
        number: true,
        email: true,
        locale: true,
        customerId: true,
        customer: { select: { firstName: true } },
        items: {
          where: { fulfillmentState: FulfillmentState.DELIVERED },
          select: {
            id: true,
            productNameSnapshot: true,
            reviews: { select: { id: true } },
          },
        },
      },
    });
    if (!order) throw new NotFoundException('لا يوجد طلب بهذا المعرّف.');

    // A guest order has no customer row to attach an invitation to, and no
    // account to sign into in order to answer it.
    if (!order.customerId) return { sent: false };

    // Nothing delivered, or everything already reviewed: no email. An
    // invitation to review something you have already reviewed is the kind of
    // message that teaches people to filter the sender.
    const pending = order.items.filter((item) => item.reviews.length === 0);
    if (pending.length === 0) return { sent: false };

    const already = await this.prisma.client.reviewInvite.findUnique({
      where: { orderId_stage: { orderId: order.id, stage } },
      select: { id: true },
    });
    if (already) return { sent: false };

    const locale = toLocale(order.locale);
    const base = process.env.STOREFRONT_URL ?? 'http://localhost:3000';
    const prefix = locale === 'en' ? '/en' : '';

    await this.mail.send({
      to: order.email,
      template: 'review.invite',
      locale,
      customerId: order.customerId,
      rendered: reviewInvite({
        locale,
        firstName: order.customer?.firstName ?? null,
        orderNumber: order.number,
        products: pending.map((item) => item.productNameSnapshot),
        url: new URL(`${prefix}${ROUTES.accountReviews}`, base).toString(),
        supportEmail: this.mail.supportEmail,
      }),
      payload: { orderNumber: order.number, stage, lines: pending.length },
    });

    // Written after the send and unconditionally: the row records that the
    // customer was asked at this stage, and a failed send that left no row
    // would ask them again on the next run.
    await this.prisma.client.reviewInvite.create({
      data: { orderId: order.id, customerId: order.customerId, stage },
    });

    return { sent: true };
  }
}
